name: "Creation-EKS"
on:
  push:
    branches: [ "main" ]

jobs:
  Plan:
    uses: BrunoAtaulo/techChallengeG24Fase3-TerraformKs8/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: LR_API_TOKEN
    secrets:
      cli_config_credentials_token: ${{ secrets.LR_API_TOKEN }}

  Apply:
    needs: Plan
    uses: BrunoAtaulo/techChallengeG24Fase3-TerraformKs8/.github/workflows/aws_tf_appy.yml@main
    with:
      gh_environment: LR_API_TOKEN
    secrets:
      cli_config_credentials_token: ${{ secrets.LR_API_TOKEN }}